---
- name: Delete MYSQL
  shell: kubectl delete deployment mysql

- name: Delete MYSQL Service
  shell: kubectl delete svc "{{mysql_service}}"

#- name: Delete MYSQL PVC
 # shell: kubectl delete pvc "{{ mysql_pv_claim }}"