---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: default
  labels:
    app: ghost
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
        tier: app
    spec:
      containers:
        - name: ghost
          image: ghost:5.14.1
          imagePullPolicy: Always
          env: # The variables below could be set on a ConfigMap object
            - name: database__client
              value: mysql
            - name: database__connection__host
              value: swap
            - name: database__connection__user
              value: swapuser
            - name: database__connection__password
              value: "123456"
            - name: database__connection__database
              value: "ghost"
            - name: url #this is wrong
              value: "http://localhost:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    matchLabels:
      app: ghost
  ports:
    - port: "{{ ghost_port }}"
      targetPort: 3000
      nodePort: 30007
