---
# Playbook to deploy Ghost and its components
# TO DO
- name: Deploy Ghost
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault/secrets.yml
  roles:
    - mysql_deploy
    - deploy_ghost
    - dashboard_deploy
