---
# Playbook to undeploy Ghost and its component
- name: Undeploy Ghost
  hosts: localhost
  roles:
    - undeploy_ghost
    - {role: mysql_undeploy, when: "delete_data is defined and delete_data == 'true'"}
