---
all:
  vars:
    # GKE cluster variables
    gcp_project: ascn-365616 # ID of GCP Project
    gcp_auth_kind: serviceaccount # Do not change
    gcp_cred_file: ./ascn-365616-644f537b1710.json # Path to service account keys (json file downloaded from GCP)

    gcp_zone: us-central1-a
    gcp_image_type: ubuntu_containerd
    gcp_machine_type: e2-micro # Can be changed if necessary
    gcp_disk_size_gb: 10 # Can be changed if necessary
    gcp_initial_node_count: 2 # Number of nodes to create. Can be changed if necessary

    # APP variables
    ghost_ip: <GHOST_SERVICE_IP> # Needs to be updated
    ghost_port: 8000 # Needs to be updated


    # Additional variables
    # ...
